name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  flake-checker:
    name: Flake checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
      - name: Run flake checker
        uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # main

  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: treefmt
          system: x86_64-linux
          os: ubuntu-latest
          cmd: 'nix build .#checks.x86_64-linux.treefmt'
        - name: check x86_64-linux
          system: x86_64-linux
          os: ubuntu-latest
          cmd: 'nix flake check'
        - name: check aarch64-linux
          system: aarch64-linux
          os: ubuntu-24.04-arm
          cmd: 'nix flake check'
        - name: build x86_64-linux
          system: x86_64-linux
          os: ubuntu-latest
          cmd: 'nix build .#nexusmods-app .#nexusmods-app-unfree'
        - name: build aarch64-linux
          system: aarch64-linux
          os: ubuntu-24.04-arm
          cmd: 'nix build .#nexusmods-app .#nexusmods-app-unfree'
    steps:
      - name: Free disk space
        uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
        with:
          hatchet-protocol: rampage
          root-safe-haven: '25600' # Default 2048
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
      - name: Setup nix cache
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: nexusmods-app-nix
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Build
        run: |
          ${{ matrix.cmd }} \
              --abort-on-warn \
              --print-build-logs \
              --log-format raw

  # A meta-job that can be referenced by GitHub Rulesets.
  # It is normally skipped, but if there was a failure it will also fail.
  check-success:
    name: Success
    runs-on: ubuntu-slim
    if: failure()
    needs:
      - build
      - flake-checker
    steps:
      - name: Failed
        run: exit 1
